# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kerry Peterson
email: kerry@xmech.net
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm Kerry. I'm a web developer at MarketDial in Salt Lake City.
  I love working with technology, rock climbing, and gaming.
  Join me while I build some things and ramble about others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.xmech.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dremex
github_username:  dremex

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge

# Custom collections
collections:
  diveLogs:
    output: true

defaults:
  - scope:
      type: "diveLogs"
    values:
      layout: "diveLog"

maps:
  google:
    api_key: AIzaSyBgt9m466yuFoT1XjLyzMVwoKwNPUVDLsI

deploy:
  - rsync -aze ssh --delete ~/code/jekyll-xmech-net/_site/. xmech.net:/var/www/xmech.net/public_html

# Pagination settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

permalink: pretty

plugins:
  - rouge
  - jekyll-feed
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
